name: perkii
description: A new Flutter project.

publish_to: 'none' # Remove this if publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase core
  firebase_core: ^4.2.0

  # Firebase authentication
  firebase_auth: ^6.1.1

  # Cloud Firestore
  cloud_firestore: ^6.0.3

  # Optional: for state management or other needs
  provider: ^6.0.6

  # Flutter material
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
